# Generated by Django 2.0.4 on 2018-05-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cet46', '0008_auto_20180512_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='cet46/static/images'),
        ),
    ]
