# Generated by Django 2.0.4 on 2018-05-13 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cet46', '0009_auto_20180512_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cet_application',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cet46.Topic', verbose_name='考试类型'),
        ),
        migrations.AlterField(
            model_name='cet_application',
            name='username',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
