# Generated by Django 2.0.4 on 2018-05-13 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cet46', '0010_auto_20180513_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cet_application',
            name='addr',
            field=models.CharField(max_length=60, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='cet_application',
            name='age',
            field=models.CharField(max_length=8, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='cet_application',
            name='gender',
            field=models.BooleanField(verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='cet_application',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者用户'),
        ),
        migrations.AlterField(
            model_name='cet_application',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='cet_application',
            name='school',
            field=models.CharField(max_length=60, verbose_name='学校名称'),
        ),
        migrations.AlterField(
            model_name='cet_application',
            name='user_id',
            field=models.CharField(max_length=18, verbose_name='身份证号'),
        ),
    ]
